import { Product } from '@/types/product'

export const mockProducts: Product[] = [
  {
    id: 1,
    name: 'Batom Cremoso Rosa Radiante',
    description: 'Fórmula suave com acabamento acetinado que realça lábios e mantém a hidratação.',
    image: 'product-1.jpg',
    price: 129,
    rating: 5,
    discount: 20,
  },
  {
    id: 2,
    name: 'Paleta Sombras Dourado',
    description: 'Mistura de tons quentes para looks sofisticados e versáteis.',
    image: 'product-2.jpg',
    price: 249,
    rating: 4,
    discount: 35,
  },
  {
    id: 3,
    name: 'Delineador Gel Black Ink',
    description: 'Longa duração e acabamento intenso para destacar o olhar.',
    image: 'product-3.jpg',
    price: 89,
    rating: 5,
    discount: 15,
  },
  {
    id: 4,
    name: 'Primer Iluminador Perolado',
    description: 'Uniformiza a pele e cria brilho saudável sob a maquiagem.',
    image: 'product-4.jpg',
    price: 109,
    rating: 4,
    discount: 20,
  },
  {
    id: 5,
    name: 'Base Adesão Matte',
    description: 'Cobertura média a alta com toque aveludado e controle de oleosidade.',
    image: 'product-5.jpg',
    price: 169,
    rating: 5,
    discount: 25,
  },
  {
    id: 6,
    name: 'Iluminador Soft Glow',
    description: 'Pigmentos micronizados entregam brilho natural sem pesar.',
    image: 'product-6.jpg',
    price: 99,
    rating: 3,
    discount: 18,
  },
  {
    id: 7,
    name: 'Blush Pó Aveludado',
    description: 'Tons rosados e queimados que se esfumam facilmente.',
    image: 'product-7.jpg',
    price: 89,
    rating: 4,
    discount: 10,
  },
  {
    id: 8,
    name: 'Máscara Cílios Volume Extremo',
    description: 'Pincel com cerdas densas para alongar e dar volume sem grumos.',
    image: 'product-8.jpg',
    price: 105,
    rating: 5,
    discount: 30,
  },
]

